services:
  - type: web
    name: ai-tutor-web-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: OPENROUTER_API_KEY
        sync: false
    healthCheckPath: /api/auth/status
    autoDeploy: true
    disk:
      name: ai-tutor-disk
      mountPath: /opt/render/project/src/data
      sizeGB: 1